/** The reviewed Great Paintings list (docs/superpowers/specs/2026-10-07-great-paintings-list.md). Hand-maintained. */

/**
 * Room order on the course home. `neighbour` orders movements for "neighbouring movement" options;
 * non-Western traditions sit apart (100+) so they neighbour each other, not a European century.
 */
export const MOVEMENTS = [
  { name: 'Ancient & Medieval', neighbour: 0 },
  { name: 'Gothic & Proto-Renaissance', neighbour: 1 },
  { name: 'Early Renaissance', neighbour: 2 },
  { name: 'Northern Renaissance', neighbour: 3 },
  { name: 'Chinese & Korean painting', neighbour: 101 },
  { name: 'High Renaissance', neighbour: 4 },
  { name: 'Venetian Renaissance', neighbour: 5 },
  { name: 'Persian & Mughal miniature', neighbour: 103 },
  { name: 'Mannerism', neighbour: 6 },
  { name: 'Japanese painting & ukiyo-e', neighbour: 102 },
  { name: 'Baroque', neighbour: 7 },
  { name: 'Dutch Golden Age', neighbour: 8 },
  { name: 'Rococo', neighbour: 9 },
  { name: 'Neoclassicism', neighbour: 10 },
  { name: 'Romanticism', neighbour: 11 },
  { name: 'Realism', neighbour: 12 },
  { name: 'Pre-Raphaelite', neighbour: 13 },
  { name: 'Impressionism', neighbour: 14 },
  { name: 'Post-Impressionism', neighbour: 15 },
  { name: 'Symbolism & Art Nouveau', neighbour: 16 },
  { name: 'Fauvism', neighbour: 17 },
  { name: 'Expressionism', neighbour: 18 },
  { name: 'Cubism & Futurism', neighbour: 19 },
  { name: 'Abstraction', neighbour: 20 },
] as const;

export type MovementName = (typeof MOVEMENTS)[number]['name'];

export interface PaintingEntry {
  key: string;
  title: string;
  /** Accepted typed titles: English, original-language and short forms. Never another painting's title. */
  titleAliases?: string[];
  /** A key of ARTISTS. */
  artist: string;
  year: string;
  movement: MovementName | string;
  alsoMovements?: string[];
  museum: string;
  fame: number;
  /** English Wikipedia article whose lead image is the painting. */
  wikipedia: string;
  /** A specific Commons file, when the lead image is wrong (a photo of the room, a frame, a print). */
  commonsFile?: string;
  /** A detail crop, as fractions of the full image. */
  crop?: { left: number; top: number; width: number; height: number };
  /** Photographed in place (cave, fresco, mural): CC BY / CC BY-SA allowed with credit. */
  inSitu?: true;
}

/**
 * Display name → accepted short forms. A surname is listed only when it is unique in the set; never a
 * first name alone. East Asian artists are known by their art name (Hokusai), Chinese masters by full name.
 */
export const ARTISTS: Record<string, string[]> = {
  'Anonymous': ['Unknown', 'Anon'],
  "Abu'l Hasan": ['Abul Hasan', 'Abu al-Hasan'],
  'Albert Gleizes': ['Gleizes'],
  'Albrecht Dürer': ['Durer', 'Duerer'],
  'Alfred Sisley': ['Sisley'],
  'Ambrogio Lorenzetti': ['Lorenzetti'],
  'Amedeo Modigliani': ['Modigliani'],
  'Andrea Mantegna': ['Mantegna'],
  'Andrei Rublev': ['Rublev', 'Andrei Rublyov'],
  'André Derain': ['Derain'],
  'Angelica Kauffman': ['Kauffman', 'Kauffmann'],
  'Anthony van Dyck': ['van Dyck', 'Dyck'],
  'Antoine Watteau': ['Watteau'],
  'Antonello da Messina': ['Antonello'],
  'Arnold Böcklin': ['Bocklin', 'Boecklin'],
  'Artemisia Gentileschi': ['Gentileschi', 'Artemisia'],
  'Behzad': ['Kamal ud-Din Behzad', 'Bihzad', 'Kamaleddin Behzad'],
  'Benjamin West': ['West'],
  'Berthe Morisot': ['Morisot'],
  'Bichitr': [],
  'Bronzino': ['Agnolo Bronzino'],
  'Camille Pissarro': ['Pissarro'],
  'Canaletto': ['Giovanni Antonio Canal'],
  'Caravaggio': ['Michelangelo Merisi da Caravaggio', 'Merisi'],
  'Carel Fabritius': ['Fabritius'],
  'Caspar David Friedrich': ['Friedrich'],
  'Chaïm Soutine': ['Soutine', 'Chaim Soutine'],
  'Claude Lorrain': ['Lorrain'],
  'Claude Monet': ['Monet'],
  'Correggio': ['Antonio Allegri'],
  'Dante Gabriel Rossetti': ['Rossetti'],
  'Diego Velázquez': ['Velazquez', 'Velasquez'],
  'Domenico Ghirlandaio': ['Ghirlandaio'],
  'Duccio': ['Duccio di Buoninsegna'],
  'Edgar Degas': ['Degas'],
  'Edvard Munch': ['Munch'],
  'Edward Burne-Jones': ['Burne-Jones'],
  'Egon Schiele': ['Schiele'],
  'El Greco': ['Greco', 'Domenikos Theotokopoulos'],
  'Emperor Huizong': ['Huizong', 'Emperor Huizong of Song'],
  'Ernst Ludwig Kirchner': ['Kirchner'],
  'Eugène Delacroix': ['Delacroix'],
  'Fan Kuan': [],
  'Fernand Léger': ['Leger'],
  'Ford Madox Brown': ['Madox Brown'],
  'Fra Angelico': ['Angelico', 'Guido di Pietro'],
  'Francisco Goya': ['Goya', 'Francisco de Goya'],
  'Frans Hals': ['Hals'],
  'Franz Marc': ['Marc'],
  'François Boucher': ['Boucher'],
  'Gentile da Fabriano': ['Gentile'],
  'Georges Seurat': ['Seurat'],
  'Georges de La Tour': ['de La Tour', 'La Tour'],
  'Gilbert Stuart': ['Stuart'],
  'Giorgione': [],
  'Giotto': ['Giotto di Bondone'],
  'Giovanni Bellini': ['Bellini'],
  'Giuseppe Arcimboldo': ['Arcimboldo'],
  'Gu Kaizhi': [],
  'Guo Xi': [],
  'Gustav Klimt': ['Klimt'],
  'Gustave Caillebotte': ['Caillebotte'],
  'Gustave Courbet': ['Courbet'],
  'Gustave Moreau': ['Moreau'],
  'Han Gan': [],
  'Hans Holbein the Younger': ['Holbein', 'Hans Holbein'],
  'Hasegawa Tōhaku': ['Tohaku'],
  'Henri Matisse': ['Matisse'],
  'Henri Rousseau': ['Rousseau', 'Le Douanier Rousseau'],
  'Henri de Toulouse-Lautrec': ['Toulouse-Lautrec', 'Lautrec'],
  'Henry Fuseli': ['Fuseli', 'Fussli'],
  'Hieronymus Bosch': ['Bosch'],
  'Hilma af Klint': ['af Klint', 'Klint'],
  'Honoré Daumier': ['Daumier'],
  'Huang Gongwang': [],
  'Ilya Repin': ['Repin'],
  'Itō Jakuchū': ['Jakuchu'],
  'Ivan Aivazovsky': ['Aivazovsky'],
  'J. M. W. Turner': ['Turner', 'J.M.W. Turner', 'Joseph Mallord William Turner', 'William Turner'],
  'Jacob van Ruisdael': ['Ruisdael', 'van Ruisdael'],
  'Jacques-Louis David': ['David'],
  'James McNeill Whistler': ['Whistler'],
  'Jan van Eyck': ['van Eyck', 'Eyck'],
  'Jean-Auguste-Dominique Ingres': ['Ingres'],
  'Jean-François Millet': ['Millet'],
  'Jean-Honoré Fragonard': ['Fragonard'],
  'Jean-Siméon Chardin': ['Chardin'],
  'Jeong Seon': ['Gyeomjae'],
  'Johannes Vermeer': ['Vermeer', 'Jan Vermeer'],
  'John Constable': ['Constable'],
  'John Everett Millais': ['Millais'],
  'John Singer Sargent': ['Sargent'],
  'John Singleton Copley': ['Copley'],
  'John William Waterhouse': ['Waterhouse'],
  'Joseph Wright of Derby': ['Wright of Derby', 'Joseph Wright'],
  'Juan Gris': ['Gris'],
  'Judith Leyster': ['Leyster'],
  'Katsushika Hokusai': ['Hokusai'],
  'Kazimir Malevich': ['Malevich'],
  'Kim Hong-do': ['Kim Hongdo', 'Danwon'],
  'Kitagawa Utamaro': ['Utamaro'],
  'Leonardo da Vinci': ['Leonardo', 'da Vinci'],
  'Limbourg brothers': ['Limbourg', 'the Limbourg brothers', 'Limbourg Brothers'],
  'Mary Cassatt': ['Cassatt'],
  'Masaccio': [],
  'Matthias Grünewald': ['Grunewald'],
  'Max Beckmann': ['Beckmann'],
  'Michelangelo': ['Michelangelo Buonarroti', 'Buonarroti'],
  'Mikhail Vrubel': ['Vrubel'],
  'Nicolas Poussin': ['Poussin'],
  'Odilon Redon': ['Redon'],
  'Ogata Kōrin': ['Korin'],
  'Paolo Uccello': ['Uccello'],
  'Paolo Veronese': ['Veronese'],
  'Parmigianino': [],
  'Paul Cézanne': ['Cezanne'],
  'Paul Gauguin': ['Gauguin'],
  'Paul Klee': ['Klee'],
  'Paula Modersohn-Becker': ['Modersohn-Becker'],
  'Peter Paul Rubens': ['Rubens'],
  'Piero della Francesca': ['della Francesca', 'Piero'],
  'Pierre-Auguste Renoir': ['Renoir'],
  'Piet Mondrian': ['Mondrian'],
  'Pieter Bruegel the Elder': ['Bruegel', 'Brueghel', 'Pieter Bruegel', 'Breughel', 'Bruegel the Elder'],
  'Pieter de Hooch': ['de Hooch', 'Hooch'],
  'Pontormo': ['Jacopo da Pontormo'],
  'Raoul Dufy': ['Dufy'],
  'Raphael': ['Raffaello', 'Raffaello Sanzio', 'Sanzio', 'Raphael Sanzio'],
  'Rembrandt': ['Rembrandt van Rijn', 'van Rijn'],
  'Reza Abbasi': ['Riza Abbasi', 'Abbasi', 'Riza-yi Abbasi'],
  'Robert Delaunay': ['Delaunay'],
  'Rogier van der Weyden': ['van der Weyden', 'Weyden'],
  'Rosa Bonheur': ['Bonheur'],
  'Sandro Botticelli': ['Botticelli'],
  'Sesshū Tōyō': ['Sesshu', 'Sesshu Toyo'],
  'Simone Martini': ['Martini'],
  'Sultan Muhammad': [],
  'Tawaraya Sōtatsu': ['Sotatsu'],
  'Thomas Cole': ['Cole'],
  'Thomas Eakins': ['Eakins'],
  'Thomas Gainsborough': ['Gainsborough'],
  'Théodore Géricault': ['Gericault'],
  'Tintoretto': ['Jacopo Tintoretto'],
  'Titian': ['Tiziano', 'Tiziano Vecellio', 'Vecellio'],
  'Umberto Boccioni': ['Boccioni'],
  'Ustad Mansur': ['Mansur'],
  'Utagawa Hiroshige': ['Hiroshige', 'Ando Hiroshige'],
  'Vincent van Gogh': ['van Gogh', 'Gogh'],
  'Wassily Kandinsky': ['Kandinsky', 'Vasily Kandinsky'],
  'William Hogarth': ['Hogarth'],
  'William Holman Hunt': ['Holman Hunt', 'Hunt'],
  'Winslow Homer': ['Homer'],
  'Zhang Zeduan': [],
  'Édouard Manet': ['Manet'],
  'Élisabeth Vigée Le Brun': ['Vigee Le Brun', 'Vigee-Lebrun', 'Le Brun'],
};

/** Typed artist answers that name no one in particular: right only for anonymous works, never a mix-up. */
export const AMBIGUOUS_ARTIST_ANSWERS = ['Anonymous', 'Unknown', 'Anon'];

export const PAINTINGS: PaintingEntry[] = [
  // Ancient & Medieval
  { key: 'lascaux', title: 'Hall of the Bulls, Lascaux', titleAliases: ['Lascaux', 'Hall of the Bulls', 'Lascaux cave paintings'], artist: 'Anonymous', year: 'c. 17,000 BCE', movement: 'Ancient & Medieval', museum: 'Lascaux cave, Dordogne', fame: 51, wikipedia: 'Lascaux', inSitu: true },
  { key: 'fowling-in-the-marshes', title: 'Fowling in the Marshes (Tomb of Nebamun)', titleAliases: ['Nebamun Hunting in the Marshes', 'Nebamun hunting birds', 'Tomb of Nebamun'], artist: 'Anonymous', year: 'c. 1350 BCE', movement: 'Ancient & Medieval', museum: 'British Museum, London', fame: 75, wikipedia: 'Fowling_in_the_Marshes_(Tomb_of_Nebamun)', inSitu: true },
  { key: 'portrait-of-a-young-woman', title: 'Portrait of a Young Woman in Red (Fayum)', titleAliases: ['Fayum portrait', 'Fayum mummy portrait', 'Portrait of a Young Woman in Red'], artist: 'Anonymous', year: 'c. 90–120', movement: 'Ancient & Medieval', museum: 'Metropolitan Museum of Art, New York', fame: 97, wikipedia: 'Portrait_of_a_Young_Woman_in_Red_(Fayum)' },
  { key: 'chi-rho-page-book-of', title: 'Chi Rho page, Book of Kells', titleAliases: ['Book of Kells', 'Chi Rho page'], artist: 'Anonymous', year: 'c. 800', movement: 'Ancient & Medieval', museum: 'Trinity College Library, Dublin', fame: 115, wikipedia: 'Chi_Rho_page,_Book_of_Kells' },
  { key: 'rublev-trinity', title: 'The Trinity', titleAliases: ['Trinity', 'Old Testament Trinity', 'Rublev Trinity'], artist: 'Andrei Rublev', year: 'c. 1411–1425', movement: 'Ancient & Medieval', museum: 'Tretyakov Gallery, Moscow', fame: 129, wikipedia: 'Trinity_(Andrei_Rublev)' },
  { key: 'villa-of-the-mysteries-frieze', title: 'Villa of the Mysteries frieze', titleAliases: ['Villa of the Mysteries', 'Dionysiac frieze'], artist: 'Anonymous', year: 'c. 60–50 BCE', movement: 'Ancient & Medieval', museum: 'Villa of the Mysteries, Pompeii', fame: 147, wikipedia: 'Villa_of_the_Mysteries_frieze', inSitu: true },
  { key: 'bodhisattva-padmapani', title: 'Bodhisattva Padmapani (Ajanta Cave 1)', titleAliases: ['Padmapani', 'Ajanta Padmapani', 'Bodhisattva Padmapani'], artist: 'Anonymous', year: 'c. 450–490', movement: 'Ancient & Medieval', museum: 'Ajanta Caves, Maharashtra', fame: 171, wikipedia: 'Bodhisattva_Padmapani_(Ajanta_Cave_1)', inSitu: true },
  { key: 'our-lady-of-vladimir', title: 'Our Lady of Vladimir', titleAliases: ['Theotokos of Vladimir', 'Vladimir Mother of God', 'Virgin of Vladimir'], artist: 'Anonymous', year: 'c. 1130', movement: 'Ancient & Medieval', museum: 'Tretyakov Gallery, Moscow', fame: 194, wikipedia: 'Our_Lady_of_Vladimir' },
  // Gothic & Proto-Renaissance
  { key: 'lamentation-giotto', title: 'Lamentation (The Mourning of Christ)', titleAliases: ['Lamentation', 'The Mourning of Christ', 'Lamentation of Christ'], artist: 'Giotto', year: 'c. 1305', movement: 'Gothic & Proto-Renaissance', museum: 'Scrovegni Chapel, Padua', fame: 52, wikipedia: 'Lamentation_(The_Mourning_of_Christ)', inSitu: true },
  { key: 'maesta', title: 'Maestà', titleAliases: ['Maesta', 'Duccio Maesta'], artist: 'Duccio', year: '1308–1311', movement: 'Gothic & Proto-Renaissance', museum: "Museo dell'Opera del Duomo, Siena", fame: 76, wikipedia: 'Maestà' },
  { key: 'tres-riches-heures-du-duc', title: 'Très Riches Heures du Duc de Berry', titleAliases: ['Tres Riches Heures', 'Les Tres Riches Heures'], artist: 'Limbourg brothers', year: 'c. 1412–1416', movement: 'Gothic & Proto-Renaissance', museum: 'Musée Condé, Chantilly', fame: 98, wikipedia: 'Très_Riches_Heures_du_Duc_de_Berry' },
  { key: 'ognissanti-madonna', title: 'Ognissanti Madonna', artist: 'Giotto', year: 'c. 1310', movement: 'Gothic & Proto-Renaissance', museum: 'Uffizi, Florence', fame: 148, wikipedia: 'Ognissanti_Madonna' },
  { key: 'annunciation-martini', title: 'Annunciation with Saint Margaret and Saint Ansanus', artist: 'Simone Martini', year: '1333', movement: 'Gothic & Proto-Renaissance', museum: 'Uffizi, Florence', fame: 172, wikipedia: 'Annunciation_with_St._Margaret_and_St._Ansanus' },
  { key: 'allegory-of-good-government', title: 'Allegory of Good Government', titleAliases: ['Effects of Good Government', 'The Allegory of Good and Bad Government', 'Good Government'], artist: 'Ambrogio Lorenzetti', year: '1338–1339', movement: 'Gothic & Proto-Renaissance', museum: 'Palazzo Pubblico, Siena', fame: 195, wikipedia: 'Allegory_of_Good_Government', inSitu: true },
  { key: 'wilton-diptych', title: 'The Wilton Diptych', titleAliases: ['Wilton Diptych'], artist: 'Anonymous', year: 'c. 1395–1399', movement: 'Gothic & Proto-Renaissance', museum: 'National Gallery, London', fame: 213, wikipedia: 'The_Wilton_Diptych' },
  { key: 'adoration-of-the-magi', title: 'Adoration of the Magi', artist: 'Gentile da Fabriano', year: '1423', movement: 'Gothic & Proto-Renaissance', museum: 'Uffizi, Florence', fame: 227, wikipedia: 'Adoration_of_the_Magi' },
  // Early Renaissance
  { key: 'birth-of-venus', title: 'The Birth of Venus', titleAliases: ['Birth of Venus', 'La nascita di Venere'], artist: 'Sandro Botticelli', year: 'c. 1484–1486', movement: 'Early Renaissance', museum: 'Uffizi, Florence', fame: 6, wikipedia: 'The_Birth_of_Venus' },
  { key: 'primavera', title: 'Primavera', titleAliases: ['Allegory of Spring', 'Spring'], artist: 'Sandro Botticelli', year: 'c. 1480', movement: 'Early Renaissance', museum: 'Uffizi, Florence', fame: 24, wikipedia: 'Primavera' },
  { key: 'holy-trinity', title: 'The Holy Trinity', titleAliases: ['Holy Trinity', 'Trinity (Masaccio)'], artist: 'Masaccio', year: 'c. 1427', movement: 'Early Renaissance', museum: 'Santa Maria Novella, Florence', fame: 53, wikipedia: 'Holy_Trinity_(Masaccio)', inSitu: true },
  { key: 'annunciation-angelico', title: 'The Annunciation (San Marco)', artist: 'Fra Angelico', year: 'c. 1440–1445', movement: 'Early Renaissance', museum: 'Convent of San Marco, Florence', fame: 77, wikipedia: 'Annunciation_(Fra_Angelico,_San_Marco)', inSitu: true },
  { key: 'flagellation-of-christ', title: 'The Flagellation of Christ', artist: 'Piero della Francesca', year: 'c. 1455–1460', movement: 'Early Renaissance', museum: 'Galleria Nazionale delle Marche, Urbino', fame: 99, wikipedia: 'The_Flagellation_of_Christ' },
  { key: 'battle-of-san-romano', title: 'The Battle of San Romano', titleAliases: ['Battle of San Romano'], artist: 'Paolo Uccello', year: 'c. 1438–1440', movement: 'Early Renaissance', museum: 'National Gallery, London', fame: 116, wikipedia: 'The_Battle_of_San_Romano' },
  { key: 'lamentation-mantegna', title: 'Lamentation over the Dead Christ', titleAliases: ['The Dead Christ', 'Dead Christ', 'Dead Christ and Three Mourners'], artist: 'Andrea Mantegna', year: 'c. 1480', movement: 'Early Renaissance', museum: 'Pinacoteca di Brera, Milan', fame: 130, wikipedia: 'Lamentation_over_the_Dead_Christ' },
  { key: 'tribute-money', title: 'The Tribute Money', artist: 'Masaccio', year: 'c. 1425', movement: 'Early Renaissance', museum: 'Brancacci Chapel, Florence', fame: 149, wikipedia: 'The_Tribute_Money', inSitu: true },
  { key: 'portraits-of-the-duke-and', title: 'Portraits of the Duke and Duchess of Urbino', artist: 'Piero della Francesca', year: 'c. 1473–1475', movement: 'Early Renaissance', museum: 'Uffizi, Florence', fame: 173, wikipedia: 'Portraits_of_the_Duke_and_Duchess_of_Urbino' },
  { key: 'camera-degli-sposi', title: 'Camera degli Sposi', artist: 'Andrea Mantegna', year: '1465–1474', movement: 'Early Renaissance', museum: 'Palazzo Ducale, Mantua', fame: 196, wikipedia: 'Camera_degli_Sposi', inSitu: true, crop: { left: 0, top: 0, width: 1, height: 1 } },
  { key: 'saint-jerome-in-his-study', title: 'Saint Jerome in His Study', artist: 'Antonello da Messina', year: 'c. 1475', movement: 'Early Renaissance', museum: 'National Gallery, London', fame: 214, wikipedia: 'Saint_Jerome_in_His_Study' },
  { key: 'old-man-and-his-grandson', title: 'An Old Man and His Grandson', artist: 'Domenico Ghirlandaio', year: 'c. 1490', movement: 'Early Renaissance', museum: 'Louvre, Paris', fame: 228, wikipedia: 'An_Old_Man_and_His_Grandson' },
  // Northern Renaissance
  { key: 'garden-of-earthly-delights', title: 'The Garden of Earthly Delights', titleAliases: ['Garden of Earthly Delights'], artist: 'Hieronymus Bosch', year: 'c. 1490–1510', movement: 'Northern Renaissance', museum: 'Prado, Madrid', fame: 14, wikipedia: 'The_Garden_of_Earthly_Delights' },
  { key: 'arnolfini', title: 'The Arnolfini Portrait', titleAliases: ['Arnolfini Portrait', 'The Arnolfini Wedding', 'Portrait of Giovanni Arnolfini and His Wife'], artist: 'Jan van Eyck', year: '1434', movement: 'Northern Renaissance', museum: 'National Gallery, London', fame: 15, wikipedia: 'The_Arnolfini_Portrait' },
  { key: 'hunters-in-the-snow', title: 'The Hunters in the Snow', titleAliases: ['Hunters in the Snow', 'Winter'], artist: 'Pieter Bruegel the Elder', year: '1565', movement: 'Northern Renaissance', museum: 'Kunsthistorisches Museum, Vienna', fame: 25, wikipedia: 'The_Hunters_in_the_Snow' },
  { key: 'tower-of-babel', title: 'The Tower of Babel', titleAliases: ['Tower of Babel'], artist: 'Pieter Bruegel the Elder', year: '1563', movement: 'Northern Renaissance', museum: 'Kunsthistorisches Museum, Vienna', fame: 38, wikipedia: 'The_Tower_of_Babel' },
  { key: 'ambassadors', title: 'The Ambassadors', artist: 'Hans Holbein the Younger', year: '1533', movement: 'Northern Renaissance', museum: 'National Gallery, London', fame: 42, wikipedia: 'The_Ambassadors' },
  { key: 'ghent-altarpiece', title: 'The Ghent Altarpiece', titleAliases: ['Ghent Altarpiece', 'Adoration of the Mystic Lamb', 'The Adoration of the Mystic Lamb'], artist: 'Jan van Eyck', year: '1432', movement: 'Northern Renaissance', museum: "St Bavo's Cathedral, Ghent", fame: 54, wikipedia: 'The_Ghent_Altarpiece' },
  { key: 'descent-from-the-cross', title: 'The Descent from the Cross', titleAliases: ['Descent from the Cross', 'Deposition', 'The Deposition'], artist: 'Rogier van der Weyden', year: 'c. 1435', movement: 'Northern Renaissance', museum: 'Prado, Madrid', fame: 78, wikipedia: 'The_Descent_from_the_Cross' },
  { key: 'self-portrait-durer', title: 'Self-Portrait at Twenty-Eight', titleAliases: ['Self-Portrait (1500)', 'Self-Portrait in a Fur-Collared Robe', 'Self-Portrait with Fur-Trimmed Robe'], artist: 'Albrecht Dürer', year: '1500', movement: 'Northern Renaissance', museum: 'Alte Pinakothek, Munich', fame: 100, wikipedia: 'Self-Portrait_(Dürer,_Munich)' },
  { key: 'young-hare', title: 'Young Hare', titleAliases: ['Hare', 'A Young Hare'], artist: 'Albrecht Dürer', year: '1502', movement: 'Northern Renaissance', museum: 'Albertina, Vienna', fame: 117, wikipedia: 'Young_Hare' },
  { key: 'portrait-of-henry-viii', title: 'Portrait of Henry VIII', artist: 'Hans Holbein the Younger', year: 'c. 1537', movement: 'Northern Renaissance', museum: 'Thyssen-Bornemisza Museum, Madrid', fame: 131, wikipedia: 'Portrait_of_Henry_VIII' },
  { key: 'netherlandish-proverbs', title: 'Netherlandish Proverbs', titleAliases: ['The Netherlandish Proverbs', 'Flemish Proverbs', 'The Blue Cloak'], artist: 'Pieter Bruegel the Elder', year: '1559', movement: 'Northern Renaissance', museum: 'Gemäldegalerie, Berlin', fame: 140, wikipedia: 'Netherlandish_Proverbs' },
  { key: 'isenheim-altarpiece', title: 'The Isenheim Altarpiece', titleAliases: ['Isenheim Altarpiece'], artist: 'Matthias Grünewald', year: '1512–1516', movement: 'Northern Renaissance', museum: 'Unterlinden Museum, Colmar', fame: 144, wikipedia: 'The_Isenheim_Altarpiece' },
  { key: 'haywain-triptych', title: 'The Haywain Triptych', titleAliases: ['Haywain', 'The Haywain'], artist: 'Hieronymus Bosch', year: 'c. 1516', movement: 'Northern Renaissance', museum: 'Prado, Madrid', fame: 150, wikipedia: 'The_Haywain_Triptych' },
  { key: 'peasant-wedding', title: 'The Peasant Wedding', artist: 'Pieter Bruegel the Elder', year: '1567', movement: 'Northern Renaissance', museum: 'Kunsthistorisches Museum, Vienna', fame: 174, wikipedia: 'The_Peasant_Wedding' },
  // Chinese & Korean painting
  { key: 'qingming', title: 'Along the River During the Qingming Festival', titleAliases: ['Qingming Shanghe Tu', 'Along the River', 'Qingming Scroll'], artist: 'Zhang Zeduan', year: 'early 12th c.', movement: 'Chinese & Korean painting', museum: 'Palace Museum, Beijing', fame: 50, wikipedia: 'Along_the_River_During_the_Qingming_Festival', crop: { left: 0, top: 0, width: 1, height: 1 } },
  { key: 'travelers-mountains', title: 'Travelers Among Mountains and Streams', titleAliases: ['Travellers Among Mountains and Streams', 'Travelers amid Mountains and Streams'], artist: 'Fan Kuan', year: 'c. 1000', movement: 'Chinese & Korean painting', museum: 'National Palace Museum, Taipei', fame: 55, wikipedia: 'Travelers_Among_Mountains_and_Streams' },
  { key: 'admonitions-of-the-instructress-to', title: 'Admonitions of the Instructress to the Court Ladies', titleAliases: ['Admonitions Scroll', 'The Admonitions Scroll'], artist: 'Gu Kaizhi', year: '5th–8th c. (Tang copy)', movement: 'Chinese & Korean painting', museum: 'British Museum, London', fame: 151, wikipedia: 'Admonitions_of_the_Instructress_to_the_Court_Ladies' },
  { key: 'night-shining-white', title: 'Night-Shining White', titleAliases: ['Night Shining White'], artist: 'Han Gan', year: 'c. 750', movement: 'Chinese & Korean painting', museum: 'Metropolitan Museum of Art, New York', fame: 175, wikipedia: 'Night-Shining_White' },
  { key: 'early-spring', title: 'Early Spring', titleAliases: ['Early Spring (Guo Xi)'], artist: 'Guo Xi', year: '1072', movement: 'Chinese & Korean painting', museum: 'National Palace Museum, Taipei', fame: 197, wikipedia: 'Early_Spring_(painting)' },
  { key: 'auspicious-cranes', title: 'Auspicious Cranes', titleAliases: ['Cranes of Good Omen'], artist: 'Emperor Huizong', year: '1112', movement: 'Chinese & Korean painting', museum: 'Liaoning Provincial Museum, Shenyang', fame: 215, wikipedia: 'Auspicious_Cranes' },
  { key: 'fuchun-mountains', title: 'Dwelling in the Fuchun Mountains', titleAliases: ['Fuchun Mountains', 'Dwelling in the Fuchun Mountains scroll'], artist: 'Huang Gongwang', year: '1347–1350', movement: 'Chinese & Korean painting', museum: 'National Palace Museum, Taipei', fame: 229, wikipedia: 'Dwelling_in_the_Fuchun_Mountains', crop: { left: 0, top: 0, width: 1, height: 1 } },
  { key: 'inwang-clearing', title: 'Clearing after Rain on Mount Inwang', titleAliases: ['Inwang Jesaekdo', 'After Rain at Mount Inwang'], artist: 'Jeong Seon', year: '1751', movement: 'Chinese & Korean painting', museum: 'Leeum Museum of Art, Seoul', fame: 239, wikipedia: 'Clearing_after_Rain_on_Mount_Inwang' },
  { key: 'ssireum', title: 'Ssireum (Wrestling)', titleAliases: ['Ssireum', 'Wrestling'], artist: 'Kim Hong-do', year: 'late 18th c.', movement: 'Chinese & Korean painting', museum: 'National Museum of Korea, Seoul', fame: 243, wikipedia: 'Ssireum_(Wrestling)' },
  // High Renaissance
  { key: 'mona-lisa', title: 'Mona Lisa', titleAliases: ['La Gioconda', 'La Joconde', 'Monna Lisa'], artist: 'Leonardo da Vinci', year: 'c. 1503–1519', movement: 'High Renaissance', museum: 'Louvre, Paris', fame: 1, wikipedia: 'Mona_Lisa' },
  { key: 'last-supper', title: 'The Last Supper', titleAliases: ['Il Cenacolo', "L'Ultima Cena"], artist: 'Leonardo da Vinci', year: '1495–1498', movement: 'High Renaissance', museum: 'Santa Maria delle Grazie, Milan', fame: 3, wikipedia: 'The_Last_Supper_(Leonardo)', inSitu: true },
  { key: 'creation-of-adam', title: 'The Creation of Adam', titleAliases: ['Creation of Adam'], artist: 'Michelangelo', year: 'c. 1512', movement: 'High Renaissance', museum: 'Sistine Chapel, Vatican', fame: 7, wikipedia: 'The_Creation_of_Adam', inSitu: true },
  { key: 'school-of-athens', title: 'The School of Athens', titleAliases: ['School of Athens', 'Scuola di Atene'], artist: 'Raphael', year: '1509–1511', movement: 'High Renaissance', museum: 'Vatican Museums', fame: 16, wikipedia: 'The_School_of_Athens', inSitu: true },
  { key: 'last-judgment', title: 'The Last Judgment', titleAliases: ['Last Judgment', 'Last Judgement', 'The Last Judgement'], artist: 'Michelangelo', year: '1536–1541', movement: 'High Renaissance', alsoMovements: ['Mannerism'], museum: 'Sistine Chapel, Vatican', fame: 28, wikipedia: 'The_Last_Judgment', inSitu: true },
  { key: 'lady-with-an-ermine', title: 'Lady with an Ermine', titleAliases: ['Portrait of Cecilia Gallerani'], artist: 'Leonardo da Vinci', year: 'c. 1489–1491', movement: 'High Renaissance', museum: 'Czartoryski Museum, Kraków', fame: 41, wikipedia: 'Lady_with_an_Ermine' },
  { key: 'virgin-of-the-rocks', title: 'Virgin of the Rocks', titleAliases: ['Madonna of the Rocks', 'The Virgin of the Rocks'], artist: 'Leonardo da Vinci', year: 'c. 1483–1486', movement: 'High Renaissance', museum: 'Louvre, Paris', fame: 56, wikipedia: 'Virgin_of_the_Rocks' },
  { key: 'doni-tondo', title: 'Doni Tondo', titleAliases: ['Holy Family (Doni Tondo)', 'The Holy Family', 'Doni Madonna'], artist: 'Michelangelo', year: 'c. 1507', movement: 'High Renaissance', alsoMovements: ['Mannerism'], museum: 'Uffizi, Florence', fame: 79, wikipedia: 'Doni_Tondo' },
  { key: 'sistine-madonna', title: 'Sistine Madonna', titleAliases: ['Madonna di San Sisto'], artist: 'Raphael', year: '1512', movement: 'High Renaissance', museum: 'Gemäldegalerie Alte Meister, Dresden', fame: 101, wikipedia: 'Sistine_Madonna' },
  { key: 'transfiguration', title: 'The Transfiguration', artist: 'Raphael', year: '1516–1520', movement: 'High Renaissance', alsoMovements: ['Mannerism'], museum: 'Vatican Museums', fame: 118, wikipedia: 'The_Transfiguration' },
  { key: 'castiglione', title: 'Portrait of Baldassare Castiglione', artist: 'Raphael', year: 'c. 1514–1515', movement: 'High Renaissance', museum: 'Louvre, Paris', fame: 152, wikipedia: 'Portrait_of_Baldassare_Castiglione' },
  { key: 'jupiter-and-io', title: 'Jupiter and Io', artist: 'Correggio', year: 'c. 1530–1532', movement: 'High Renaissance', alsoMovements: ['Mannerism'], museum: 'Kunsthistorisches Museum, Vienna', fame: 176, wikipedia: 'Jupiter_and_Io' },
  // Venetian Renaissance
  { key: 'venus-of-urbino', title: 'Venus of Urbino', titleAliases: ['Venere di Urbino'], artist: 'Titian', year: '1538', movement: 'Venetian Renaissance', museum: 'Uffizi, Florence', fame: 45, wikipedia: 'Venus_of_Urbino' },
  { key: 'bacchus-and-ariadne', title: 'Bacchus and Ariadne', artist: 'Titian', year: '1520–1523', movement: 'Venetian Renaissance', museum: 'National Gallery, London', fame: 57, wikipedia: 'Bacchus_and_Ariadne' },
  { key: 'assumption-of-the-virgin', title: 'Assumption of the Virgin', titleAliases: ['Assunta', 'Assumption of the Virgin (Frari)'], artist: 'Titian', year: '1516–1518', movement: 'Venetian Renaissance', museum: 'Frari, Venice', fame: 80, wikipedia: 'Assumption_of_the_Virgin_(Titian)' },
  { key: 'tempest', title: 'The Tempest', titleAliases: ['La Tempesta', 'Tempest'], artist: 'Giorgione', year: 'c. 1508', movement: 'Venetian Renaissance', museum: "Gallerie dell'Accademia, Venice", fame: 102, wikipedia: 'The_Tempest_(Giorgione)' },
  { key: 'wedding-at-cana', title: 'The Wedding at Cana', titleAliases: ['Wedding at Cana', 'Wedding Feast at Cana'], artist: 'Paolo Veronese', year: '1563', movement: 'Venetian Renaissance', museum: 'Louvre, Paris', fame: 119, wikipedia: 'The_Wedding_at_Cana' },
  { key: 'sacred-and-profane-love', title: 'Sacred and Profane Love', artist: 'Titian', year: 'c. 1514', movement: 'Venetian Renaissance', museum: 'Galleria Borghese, Rome', fame: 153, wikipedia: 'Sacred_and_Profane_Love' },
  { key: 'sleeping-venus', title: 'Sleeping Venus', artist: 'Giorgione', year: 'c. 1510', movement: 'Venetian Renaissance', museum: 'Gemäldegalerie Alte Meister, Dresden', fame: 177, wikipedia: 'Sleeping_Venus_(Giorgione)' },
  { key: 'saint-francis-in-the-desert', title: 'Saint Francis in the Desert', titleAliases: ['St Francis in Ecstasy', 'St. Francis in the Desert', 'Saint Francis in Ecstasy'], artist: 'Giovanni Bellini', year: 'c. 1476–1478', movement: 'Venetian Renaissance', museum: 'Frick Collection, New York', fame: 198, wikipedia: 'Saint_Francis_in_the_Desert' },
  { key: 'last-supper-tintoretto', title: 'The Last Supper (San Giorgio Maggiore)', artist: 'Tintoretto', year: '1592–1594', movement: 'Venetian Renaissance', alsoMovements: ['Mannerism'], museum: 'San Giorgio Maggiore, Venice', fame: 216, wikipedia: 'The_Last_Supper_(Tintoretto)' },
  // Persian & Mughal miniature
  { key: 'court-of-gayumars', title: 'The Court of Gayumars', titleAliases: ['Court of Gayumars', 'The Court of Kayumars'], artist: 'Sultan Muhammad', year: 'c. 1522–1525', movement: 'Persian & Mughal miniature', museum: 'Aga Khan Museum, Toronto', fame: 58, wikipedia: 'The_Court_of_Gayumars' },
  { key: 'seduction-of-yusuf', title: 'The Seduction of Yusuf', titleAliases: ['Seduction of Yusuf', 'Yusuf and Zulaikha'], artist: 'Behzad', year: '1488', movement: 'Persian & Mughal miniature', museum: 'National Library and Archives, Cairo', fame: 154, wikipedia: 'The_Seduction_of_Yusuf' },
  { key: 'squirrels-in-a-plane-tree', title: 'Squirrels in a Plane Tree', artist: "Abu'l Hasan", year: 'c. 1610', movement: 'Persian & Mughal miniature', museum: 'British Library, London', fame: 178, wikipedia: 'Squirrels_in_a_Plane_Tree' },
  { key: 'turkey-cock', title: 'Turkey Cock', artist: 'Ustad Mansur', year: 'c. 1612', movement: 'Persian & Mughal miniature', museum: 'Victoria and Albert Museum, London', fame: 199, wikipedia: 'Turkey_Cock' },
  { key: 'jahangir-preferring-a-sufi-shaikh', title: 'Jahangir Preferring a Sufi Shaikh to Kings', titleAliases: ['Jahangir Preferring a Sufi Shaikh'], artist: 'Bichitr', year: 'c. 1615–1618', movement: 'Persian & Mughal miniature', museum: 'Freer Gallery of Art, Washington', fame: 217, wikipedia: 'Jahangir_Preferring_a_Sufi_Shaikh_to_Kings' },
  { key: 'two-lovers', title: 'Two Lovers', artist: 'Reza Abbasi', year: '1630', movement: 'Persian & Mughal miniature', museum: 'Metropolitan Museum of Art, New York', fame: 230, wikipedia: 'Two_Lovers' },
  // Mannerism
  { key: 'madonna-with-the-long-neck', title: 'Madonna with the Long Neck', titleAliases: ['Madonna dal collo lungo', 'Madonna of the Long Neck'], artist: 'Parmigianino', year: 'c. 1535–1540', movement: 'Mannerism', museum: 'Uffizi, Florence', fame: 59, wikipedia: 'Madonna_with_the_Long_Neck' },
  { key: 'allegory-with-venus-and-cupid', title: 'An Allegory with Venus and Cupid', titleAliases: ['Venus, Cupid, Folly and Time', 'Allegory with Venus and Cupid', 'Allegory of Venus and Cupid'], artist: 'Bronzino', year: 'c. 1545', movement: 'Mannerism', museum: 'National Gallery, London', fame: 81, wikipedia: 'An_Allegory_with_Venus_and_Cupid' },
  { key: 'burial-of-the-count-of', title: 'The Burial of the Count of Orgaz', titleAliases: ['Burial of the Count of Orgaz'], artist: 'El Greco', year: '1586–1588', movement: 'Mannerism', museum: 'Santo Tomé, Toledo', fame: 103, wikipedia: 'The_Burial_of_the_Count_of_Orgaz' },
  { key: 'view-of-toledo', title: 'View of Toledo', artist: 'El Greco', year: 'c. 1599–1600', movement: 'Mannerism', museum: 'Metropolitan Museum of Art, New York', fame: 120, wikipedia: 'View_of_Toledo' },
  { key: 'vertumnus', title: 'Vertumnus', artist: 'Giuseppe Arcimboldo', year: 'c. 1590–1591', movement: 'Mannerism', museum: 'Skokloster Castle, Sweden', fame: 132, wikipedia: 'Vertumnus' },
  { key: 'self-portrait-in-a-convex', title: 'Self-Portrait in a Convex Mirror', artist: 'Parmigianino', year: 'c. 1524', movement: 'Mannerism', museum: 'Kunsthistorisches Museum, Vienna', fame: 155, wikipedia: 'Self-Portrait_in_a_Convex_Mirror' },
  { key: 'eleonora-of-toledo-with-her', title: 'Eleonora of Toledo with Her Son Giovanni', artist: 'Bronzino', year: 'c. 1545', movement: 'Mannerism', museum: 'Uffizi, Florence', fame: 179, wikipedia: 'Eleonora_of_Toledo_with_Her_Son_Giovanni' },
  { key: 'deposition-from-the-cross', title: 'The Deposition from the Cross', artist: 'Pontormo', year: '1525–1528', movement: 'Mannerism', museum: 'Santa Felicita, Florence', fame: 200, wikipedia: 'The_Deposition_from_the_Cross' },
  // Japanese painting & ukiyo-e
  { key: 'great-wave', title: 'The Great Wave off Kanagawa', titleAliases: ['The Great Wave', 'Great Wave', 'Under the Wave off Kanagawa'], artist: 'Katsushika Hokusai', year: 'c. 1831', movement: 'Japanese painting & ukiyo-e', museum: 'Many impressions (e.g. Met, British Museum)', fame: 8, wikipedia: 'The_Great_Wave_off_Kanagawa' },
  { key: 'three-beauties-of-the-present', title: 'Three Beauties of the Present Day', titleAliases: ['Three Beauties'], artist: 'Kitagawa Utamaro', year: 'c. 1793', movement: 'Japanese painting & ukiyo-e', museum: 'Many impressions (e.g. Museum of Fine Arts, Boston)', fame: 60, wikipedia: 'Three_Beauties_of_the_Present_Day' },
  { key: 'irises-korin', title: 'Irises', titleAliases: ['Irises Screens', 'Irises (Korin)'], artist: 'Ogata Kōrin', year: 'c. 1701–1705', movement: 'Japanese painting & ukiyo-e', museum: 'Nezu Museum, Tokyo', fame: 82, wikipedia: 'Irises_(Ogata_Kōrin)' },
  { key: 'fine-wind-clear-morning', title: 'Fine Wind, Clear Morning (Red Fuji)', titleAliases: ['Red Fuji', 'Fine Wind Clear Morning', 'South Wind, Clear Sky'], artist: 'Katsushika Hokusai', year: 'c. 1831', movement: 'Japanese painting & ukiyo-e', museum: 'Many impressions (e.g. Met, British Museum)', fame: 104, wikipedia: 'Fine_Wind,_Clear_Morning_(Red_Fuji)' },
  { key: 'sudden-shower', title: 'Sudden Shower over Shin-Ōhashi Bridge and Atake', titleAliases: ['Sudden Shower over Shin-Ohashi Bridge', 'Sudden Shower at Atake', 'Ohashi Bridge in the Rain'], artist: 'Utagawa Hiroshige', year: '1857', movement: 'Japanese painting & ukiyo-e', museum: 'Many impressions (e.g. Brooklyn Museum)', fame: 121, wikipedia: 'Sudden_Shower_over_Shin-Ōhashi_Bridge_and_Atake' },
  { key: 'winter-landscape', title: 'Winter Landscape', artist: 'Sesshū Tōyō', year: 'c. 1470s', movement: 'Japanese painting & ukiyo-e', museum: 'Tokyo National Museum', fame: 156, wikipedia: 'Winter_Landscape' },
  { key: 'pine-trees', title: 'Pine Trees', titleAliases: ['Pine Trees Screen', 'Shorin-zu'], artist: 'Hasegawa Tōhaku', year: 'c. 1595', movement: 'Japanese painting & ukiyo-e', museum: 'Tokyo National Museum', fame: 180, wikipedia: 'Pine_Trees' },
  { key: 'wind-god-and-thunder-god', title: 'Wind God and Thunder God', titleAliases: ['Fujin and Raijin', 'Fujin Raijin-zu'], artist: 'Tawaraya Sōtatsu', year: 'early 17th c.', movement: 'Japanese painting & ukiyo-e', museum: 'Kennin-ji, Kyoto', fame: 201, wikipedia: 'Wind_God_and_Thunder_God' },
  { key: 'rooster-hen-and-hydrangea', title: 'Rooster, Hen and Hydrangea', titleAliases: ['Rooster and Hen with Hydrangeas'], artist: 'Itō Jakuchū', year: 'c. 1757–1766', movement: 'Japanese painting & ukiyo-e', museum: 'Museum of the Imperial Collections, Tokyo', fame: 218, wikipedia: 'Rooster,_Hen_and_Hydrangea' },
  { key: 'plum-park', title: 'Plum Park in Kameido', titleAliases: ['Plum Garden in Kameido', 'Plum Estate, Kameido'], artist: 'Utagawa Hiroshige', year: '1857', movement: 'Japanese painting & ukiyo-e', museum: 'Many impressions (e.g. Brooklyn Museum)', fame: 231, wikipedia: 'Plum_Park_in_Kameido' },
  // Baroque
  { key: 'las-meninas', title: 'Las Meninas', titleAliases: ['The Ladies-in-waiting', 'The Family of Philip IV'], artist: 'Diego Velázquez', year: '1656', movement: 'Baroque', museum: 'Prado, Madrid', fame: 11, wikipedia: 'Las_Meninas' },
  { key: 'calling-of-st-matthew', title: 'The Calling of Saint Matthew', artist: 'Caravaggio', year: '1599–1600', movement: 'Baroque', museum: 'San Luigi dei Francesi, Rome', fame: 61, wikipedia: 'The_Calling_of_Saint_Matthew' },
  { key: 'judith-caravaggio', title: 'Judith Beheading Holofernes', artist: 'Caravaggio', year: 'c. 1599', movement: 'Baroque', museum: 'Palazzo Barberini, Rome', fame: 83, wikipedia: 'Judith_Beheading_Holofernes_(Caravaggio)' },
  { key: 'judith-gentileschi', title: 'Judith Slaying Holofernes', artist: 'Artemisia Gentileschi', year: 'c. 1620', movement: 'Baroque', museum: 'Uffizi, Florence', fame: 105, wikipedia: 'Judith_Slaying_Holofernes_(Artemisia_Gentileschi,_Naples)' },
  { key: 'rokeby-venus', title: 'The Rokeby Venus', titleAliases: ['Rokeby Venus', 'The Toilet of Venus', 'Venus at Her Mirror'], artist: 'Diego Velázquez', year: '1647–1651', movement: 'Baroque', museum: 'National Gallery, London', fame: 122, wikipedia: 'The_Rokeby_Venus' },
  { key: 'innocent-x', title: 'Portrait of Pope Innocent X', titleAliases: ['Pope Innocent X', 'Innocent X'], artist: 'Diego Velázquez', year: 'c. 1650', movement: 'Baroque', museum: 'Galleria Doria Pamphilj, Rome', fame: 133, wikipedia: 'Portrait_of_Pope_Innocent_X' },
  { key: 'supper-at-emmaus', title: 'Supper at Emmaus', artist: 'Caravaggio', year: '1601', movement: 'Baroque', museum: 'National Gallery, London', fame: 157, wikipedia: 'Supper_at_Emmaus' },
  { key: 'self-portrait-allegory-painting', title: 'Self-Portrait as the Allegory of Painting', artist: 'Artemisia Gentileschi', year: 'c. 1638–1639', movement: 'Baroque', museum: 'Royal Collection, London', fame: 181, wikipedia: 'Self-Portrait_as_the_Allegory_of_Painting' },
  { key: 'elevation-of-the-cross', title: 'The Elevation of the Cross', artist: 'Peter Paul Rubens', year: '1610–1611', movement: 'Baroque', museum: 'Antwerp Cathedral', fame: 202, wikipedia: 'The_Elevation_of_the_Cross' },
  { key: 'three-graces', title: 'The Three Graces', artist: 'Peter Paul Rubens', year: 'c. 1630–1635', movement: 'Baroque', museum: 'Prado, Madrid', fame: 219, wikipedia: 'The_Three_Graces' },
  { key: 'charles-i-hunt', title: 'Charles I at the Hunt', artist: 'Anthony van Dyck', year: 'c. 1635', movement: 'Baroque', museum: 'Louvre, Paris', fame: 232, wikipedia: 'Charles_I_at_the_Hunt' },
  { key: 'et-in-arcadia-ego', title: 'Et in Arcadia ego', titleAliases: ['The Arcadian Shepherds', 'Les Bergers d Arcadie'], artist: 'Nicolas Poussin', year: '1637–1638', movement: 'Baroque', museum: 'Louvre, Paris', fame: 240, wikipedia: 'Et_in_Arcadia_ego' },
  { key: 'seaport-with-the-embarkation-of', title: 'Seaport with the Embarkation of the Queen of Sheba', artist: 'Claude Lorrain', year: '1648', movement: 'Baroque', museum: 'National Gallery, London', fame: 244, wikipedia: 'Seaport_with_the_Embarkation_of_the_Queen_of_Sheba' },
  { key: 'cheat-ace-of-diamonds', title: 'The Cheat with the Ace of Diamonds', artist: 'Georges de La Tour', year: 'c. 1636–1638', movement: 'Baroque', museum: 'Louvre, Paris', fame: 246, wikipedia: 'The_Cheat_with_the_Ace_of_Diamonds' },
  // Dutch Golden Age
  { key: 'girl-with-a-pearl-earring', title: 'Girl with a Pearl Earring', titleAliases: ['Girl with the Pearl Earring'], artist: 'Johannes Vermeer', year: 'c. 1665', movement: 'Dutch Golden Age', museum: 'Mauritshuis, The Hague', fame: 4, wikipedia: 'Girl_with_a_Pearl_Earring' },
  { key: 'night-watch', title: 'The Night Watch', titleAliases: ['Night Watch', 'The Militia Company of Captain Frans Banninck Cocq'], artist: 'Rembrandt', year: '1642', movement: 'Dutch Golden Age', museum: 'Rijksmuseum, Amsterdam', fame: 9, wikipedia: 'The_Night_Watch' },
  { key: 'milkmaid', title: 'The Milkmaid', titleAliases: ['The Kitchen Maid', 'Milkmaid'], artist: 'Johannes Vermeer', year: 'c. 1658', movement: 'Dutch Golden Age', museum: 'Rijksmuseum, Amsterdam', fame: 26, wikipedia: 'The_Milkmaid' },
  { key: 'anatomy-lesson', title: 'The Anatomy Lesson of Dr Nicolaes Tulp', titleAliases: ['The Anatomy Lesson', 'Anatomy Lesson of Dr. Tulp', 'The Anatomy Lesson of Dr Tulp'], artist: 'Rembrandt', year: '1632', movement: 'Dutch Golden Age', museum: 'Mauritshuis, The Hague', fame: 62, wikipedia: 'The_Anatomy_Lesson_of_Dr_Nicolaes_Tulp' },
  { key: 'self-portrait-two-circles', title: 'Self-Portrait with Two Circles', titleAliases: ['Self-Portrait with Two Circles (Kenwood)'], artist: 'Rembrandt', year: 'c. 1665–1669', movement: 'Dutch Golden Age', museum: 'Kenwood House, London', fame: 84, wikipedia: 'Self-Portrait_with_Two_Circles' },
  { key: 'return-of-the-prodigal-son', title: 'The Return of the Prodigal Son', titleAliases: ['Return of the Prodigal Son', 'The Prodigal Son'], artist: 'Rembrandt', year: 'c. 1668', movement: 'Dutch Golden Age', museum: 'Hermitage, St Petersburg', fame: 106, wikipedia: 'The_Return_of_the_Prodigal_Son' },
  { key: 'view-of-delft', title: 'View of Delft', artist: 'Johannes Vermeer', year: 'c. 1660–1661', movement: 'Dutch Golden Age', museum: 'Mauritshuis, The Hague', fame: 123, wikipedia: 'View_of_Delft' },
  { key: 'art-of-painting', title: 'The Art of Painting', artist: 'Johannes Vermeer', year: 'c. 1666–1668', movement: 'Dutch Golden Age', museum: 'Kunsthistorisches Museum, Vienna', fame: 134, wikipedia: 'The_Art_of_Painting' },
  { key: 'laughing-cavalier', title: 'The Laughing Cavalier', titleAliases: ['Laughing Cavalier'], artist: 'Frans Hals', year: '1624', movement: 'Dutch Golden Age', museum: 'Wallace Collection, London', fame: 141, wikipedia: 'The_Laughing_Cavalier' },
  { key: 'goldfinch', title: 'The Goldfinch', titleAliases: ['Goldfinch'], artist: 'Carel Fabritius', year: '1654', movement: 'Dutch Golden Age', museum: 'Mauritshuis, The Hague', fame: 145, wikipedia: 'The_Goldfinch' },
  { key: 'courtyard-delft', title: 'The Courtyard of a House in Delft', artist: 'Pieter de Hooch', year: '1658', movement: 'Dutch Golden Age', museum: 'National Gallery, London', fame: 158, wikipedia: 'The_Courtyard_of_a_House_in_Delft' },
  { key: 'windmill-wijk', title: 'The Windmill at Wijk bij Duurstede', artist: 'Jacob van Ruisdael', year: 'c. 1668–1670', movement: 'Dutch Golden Age', museum: 'Rijksmuseum, Amsterdam', fame: 182, wikipedia: 'The_Windmill_at_Wijk_bij_Duurstede' },
  { key: 'self-portrait-leyster', title: 'Self-Portrait at the Easel', artist: 'Judith Leyster', year: 'c. 1630', movement: 'Dutch Golden Age', museum: 'National Gallery of Art, Washington', fame: 203, wikipedia: 'Self-portrait_(Judith_Leyster)' },
  // Rococo
  { key: 'swing', title: 'The Swing', titleAliases: ["Les Hasards heureux de l'escarpolette", 'The Happy Accidents of the Swing'], artist: 'Jean-Honoré Fragonard', year: '1767', movement: 'Rococo', museum: 'Wallace Collection, London', fame: 35, wikipedia: 'The_Swing_(Fragonard)' },
  { key: 'pilgrimage-to-cythera', title: 'Pilgrimage to Cythera', titleAliases: ['The Embarkation for Cythera', 'Embarkation for Cythera'], artist: 'Antoine Watteau', year: '1717', movement: 'Rococo', museum: 'Louvre, Paris', fame: 63, wikipedia: 'Pilgrimage_to_Cythera' },
  { key: 'mr-and-mrs-andrews', title: 'Mr and Mrs Andrews', titleAliases: ['Mr. and Mrs. Andrews'], artist: 'Thomas Gainsborough', year: 'c. 1750', movement: 'Rococo', museum: 'National Gallery, London', fame: 85, wikipedia: 'Mr_and_Mrs_Andrews' },
  { key: 'blue-boy', title: 'The Blue Boy', titleAliases: ['Blue Boy'], artist: 'Thomas Gainsborough', year: 'c. 1770', movement: 'Rococo', museum: 'Huntington Library, San Marino', fame: 107, wikipedia: 'The_Blue_Boy' },
  { key: 'pierrot', title: 'Pierrot (Gilles)', titleAliases: ['Pierrot', 'Gilles'], artist: 'Antoine Watteau', year: 'c. 1718–1719', movement: 'Rococo', museum: 'Louvre, Paris', fame: 159, wikipedia: 'Pierrot_(Gilles)' },
  { key: 'madame-de-pompadour', title: 'Madame de Pompadour', titleAliases: ['Portrait of Madame de Pompadour'], artist: 'François Boucher', year: '1756', movement: 'Rococo', museum: 'Alte Pinakothek, Munich', fame: 183, wikipedia: 'Madame_de_Pompadour' },
  { key: 'stonemasons-yard', title: "The Stonemason's Yard", artist: 'Canaletto', year: 'c. 1725', movement: 'Rococo', museum: 'National Gallery, London', fame: 204, wikipedia: "The_Stonemason's_Yard" },
  { key: 'marriage-a-la-mode-the', title: 'Marriage A-la-Mode: The Tête à Tête', titleAliases: ['Marriage A-la-Mode', 'The Tete a Tete', 'Marriage a la Mode'], artist: 'William Hogarth', year: 'c. 1743', movement: 'Rococo', museum: 'National Gallery, London', fame: 220, wikipedia: 'Marriage_A-la-Mode:_The_Tête_à_Tête' },
  { key: 'self-portrait-straw-hat', title: 'Self-Portrait in a Straw Hat', artist: 'Élisabeth Vigée Le Brun', year: '1782', movement: 'Rococo', alsoMovements: ['Neoclassicism'], museum: 'National Gallery, London', fame: 233, wikipedia: 'Self-Portrait_in_a_Straw_Hat' },
  { key: 'soap-bubbles', title: 'Soap Bubbles', titleAliases: ['Soap Bubbles (Chardin)'], artist: 'Jean-Siméon Chardin', year: 'c. 1733–1734', movement: 'Rococo', museum: 'Metropolitan Museum of Art, New York', fame: 241, wikipedia: 'Soap_Bubbles' },
  // Neoclassicism
  { key: 'death-of-marat', title: 'The Death of Marat', titleAliases: ['Death of Marat', 'Marat Assassinated'], artist: 'Jacques-Louis David', year: '1793', movement: 'Neoclassicism', museum: 'Royal Museums of Fine Arts, Brussels', fame: 36, wikipedia: 'The_Death_of_Marat' },
  { key: 'napoleon-crossing-the-alps', title: 'Napoleon Crossing the Alps', titleAliases: ['Bonaparte Crossing the Alps', 'Napoleon at the Saint-Bernard Pass'], artist: 'Jacques-Louis David', year: '1801', movement: 'Neoclassicism', alsoMovements: ['Romanticism'], museum: 'Château de Malmaison', fame: 37, wikipedia: 'Napoleon_Crossing_the_Alps' },
  { key: 'oath-of-the-horatii', title: 'Oath of the Horatii', titleAliases: ['The Oath of the Horatii'], artist: 'Jacques-Louis David', year: '1784', movement: 'Neoclassicism', museum: 'Louvre, Paris', fame: 64, wikipedia: 'Oath_of_the_Horatii' },
  { key: 'coronation-of-napoleon', title: 'The Coronation of Napoleon', titleAliases: ['Coronation of Napoleon', 'The Consecration of the Emperor Napoleon'], artist: 'Jacques-Louis David', year: '1805–1807', movement: 'Neoclassicism', museum: 'Louvre, Paris', fame: 86, wikipedia: 'The_Coronation_of_Napoleon' },
  { key: 'grande-odalisque', title: 'La Grande Odalisque', titleAliases: ['Grande Odalisque', 'Une Odalisque'], artist: 'Jean-Auguste-Dominique Ingres', year: '1814', movement: 'Neoclassicism', alsoMovements: ['Romanticism'], museum: 'Louvre, Paris', fame: 108, wikipedia: 'La_Grande_Odalisque' },
  { key: 'experiment-on-a-bird-in', title: 'An Experiment on a Bird in the Air Pump', titleAliases: ['Experiment on a Bird in the Air Pump', 'The Air Pump'], artist: 'Joseph Wright of Derby', year: '1768', movement: 'Neoclassicism', alsoMovements: ['Romanticism'], museum: 'National Gallery, London', fame: 124, wikipedia: 'An_Experiment_on_a_Bird_in_the_Air_Pump' },
  { key: 'george-washington', title: 'George Washington (The Athenaeum Portrait)', titleAliases: ['The Athenaeum Portrait', 'Athenaeum Portrait', 'George Washington'], artist: 'Gilbert Stuart', year: '1796', movement: 'Neoclassicism', museum: 'National Portrait Gallery, Washington', fame: 135, wikipedia: 'George_Washington_(The_Athenaeum_Portrait)' },
  { key: 'death-of-general-wolfe', title: 'The Death of General Wolfe', artist: 'Benjamin West', year: '1770', movement: 'Neoclassicism', museum: 'National Gallery of Canada, Ottawa', fame: 160, wikipedia: 'The_Death_of_General_Wolfe' },
  { key: 'watson-and-the-shark', title: 'Watson and the Shark', artist: 'John Singleton Copley', year: '1778', movement: 'Neoclassicism', alsoMovements: ['Romanticism'], museum: 'National Gallery of Art, Washington', fame: 184, wikipedia: 'Watson_and_the_Shark' },
  { key: 'cornelia-mother-of-the-gracchi', title: 'Cornelia, Mother of the Gracchi', artist: 'Angelica Kauffman', year: 'c. 1785', movement: 'Neoclassicism', museum: 'Virginia Museum of Fine Arts, Richmond', fame: 205, wikipedia: 'Cornelia,_Mother_of_the_Gracchi' },
  // Romanticism
  { key: 'liberty-leading-the-people', title: 'Liberty Leading the People', titleAliases: ['La Liberte guidant le peuple', 'Liberty'], artist: 'Eugène Delacroix', year: '1830', movement: 'Romanticism', museum: 'Louvre, Paris', fame: 17, wikipedia: 'Liberty_Leading_the_People' },
  { key: 'wanderer', title: 'Wanderer above the Sea of Fog', titleAliases: ['Wanderer above the Mists', 'The Wanderer', 'Wanderer over the Sea of Fog'], artist: 'Caspar David Friedrich', year: 'c. 1818', movement: 'Romanticism', museum: 'Hamburger Kunsthalle', fame: 18, wikipedia: 'Wanderer_above_the_Sea_of_Fog' },
  { key: 'third-of-may', title: 'The Third of May 1808', titleAliases: ['The Third of May', 'The 3rd of May 1808', 'Third of May'], artist: 'Francisco Goya', year: '1814', movement: 'Romanticism', museum: 'Prado, Madrid', fame: 21, wikipedia: 'The_Third_of_May_1808' },
  { key: 'raft-of-the-medusa', title: 'The Raft of the Medusa', titleAliases: ['Raft of the Medusa', 'Le Radeau de la Meduse'], artist: 'Théodore Géricault', year: '1818–1819', movement: 'Romanticism', museum: 'Louvre, Paris', fame: 22, wikipedia: 'The_Raft_of_the_Medusa' },
  { key: 'hay-wain', title: 'The Hay Wain', titleAliases: ['Hay Wain'], artist: 'John Constable', year: '1821', movement: 'Romanticism', museum: 'National Gallery, London', fame: 39, wikipedia: 'The_Hay_Wain' },
  { key: 'fighting-temeraire', title: 'The Fighting Temeraire', titleAliases: ['The Fighting Temeraire tugged to her last berth to be broken up', 'Fighting Temeraire'], artist: 'J. M. W. Turner', year: '1839', movement: 'Romanticism', museum: 'National Gallery, London', fame: 40, wikipedia: 'The_Fighting_Temeraire' },
  { key: 'saturn-devouring-his-son', title: 'Saturn Devouring His Son', titleAliases: ['Saturn', 'Saturn Devouring One of His Sons'], artist: 'Francisco Goya', year: 'c. 1819–1823', movement: 'Romanticism', museum: 'Prado, Madrid', fame: 47, wikipedia: 'Saturn_Devouring_His_Son' },
  { key: 'sea-of-ice', title: 'The Sea of Ice', artist: 'Caspar David Friedrich', year: '1823–1824', movement: 'Romanticism', museum: 'Hamburger Kunsthalle', fame: 65, wikipedia: 'The_Sea_of_Ice' },
  { key: 'death-of-sardanapalus', title: 'The Death of Sardanapalus', titleAliases: ['Death of Sardanapalus'], artist: 'Eugène Delacroix', year: '1827', movement: 'Romanticism', museum: 'Louvre, Paris', fame: 87, wikipedia: 'The_Death_of_Sardanapalus' },
  { key: 'nude-maja', title: 'The Nude Maja', titleAliases: ['La maja desnuda', 'Nude Maja'], artist: 'Francisco Goya', year: 'c. 1797–1800', movement: 'Romanticism', museum: 'Prado, Madrid', fame: 109, wikipedia: 'The_Nude_Maja' },
  { key: 'rain-steam-and-speed', title: 'Rain, Steam and Speed', titleAliases: ['Rain Steam and Speed', 'Rain, Steam and Speed – The Great Western Railway'], artist: 'J. M. W. Turner', year: '1844', movement: 'Romanticism', museum: 'National Gallery, London', fame: 125, wikipedia: 'Rain,_Steam_and_Speed' },
  { key: 'nightmare', title: 'The Nightmare', titleAliases: ['Nightmare'], artist: 'Henry Fuseli', year: '1781', movement: 'Romanticism', museum: 'Detroit Institute of Arts', fame: 136, wikipedia: 'The_Nightmare' },
  { key: 'ninth-wave', title: 'The Ninth Wave', titleAliases: ['Ninth Wave'], artist: 'Ivan Aivazovsky', year: '1850', movement: 'Romanticism', museum: 'Russian Museum, St Petersburg', fame: 142, wikipedia: 'The_Ninth_Wave' },
  { key: 'oxbow', title: 'The Oxbow', titleAliases: ['View from Mount Holyoke', 'Oxbow'], artist: 'Thomas Cole', year: '1836', movement: 'Romanticism', museum: 'Metropolitan Museum of Art, New York', fame: 161, wikipedia: 'The_Oxbow' },
  // Realism
  { key: 'whistlers-mother', title: "Whistler's Mother", titleAliases: ['Arrangement in Grey and Black No. 1', 'Arrangement in Grey and Black'], artist: 'James McNeill Whistler', year: '1871', movement: 'Realism', alsoMovements: ['Symbolism & Art Nouveau'], museum: "Musée d'Orsay, Paris", fame: 23, wikipedia: "Whistler's_Mother" },
  { key: 'olympia', title: 'Olympia', artist: 'Édouard Manet', year: '1863', movement: 'Realism', alsoMovements: ['Impressionism'], museum: "Musée d'Orsay, Paris", fame: 29, wikipedia: 'Olympia_(Manet)' },
  { key: 'burial-at-ornans', title: 'A Burial at Ornans', titleAliases: ['Burial at Ornans'], artist: 'Gustave Courbet', year: '1849–1850', movement: 'Realism', museum: "Musée d'Orsay, Paris", fame: 66, wikipedia: 'A_Burial_at_Ornans' },
  { key: 'gleaners', title: 'The Gleaners', titleAliases: ['Gleaners', 'Des glaneuses'], artist: 'Jean-François Millet', year: '1857', movement: 'Realism', museum: "Musée d'Orsay, Paris", fame: 88, wikipedia: 'The_Gleaners' },
  { key: 'angelus', title: 'The Angelus', titleAliases: ["L'Angelus", 'Angelus'], artist: 'Jean-François Millet', year: '1857–1859', movement: 'Realism', museum: "Musée d'Orsay, Paris", fame: 110, wikipedia: 'The_Angelus' },
  { key: 'dejeuner-sur-lherbe', title: "Le Déjeuner sur l'herbe", titleAliases: ['The Luncheon on the Grass', 'Luncheon on the Grass', 'Dejeuner sur l herbe'], artist: 'Édouard Manet', year: '1863', movement: 'Realism', alsoMovements: ['Impressionism'], museum: "Musée d'Orsay, Paris", fame: 126, wikipedia: "Le_Déjeuner_sur_l'herbe" },
  { key: 'bar-folies-bergere', title: 'A Bar at the Folies-Bergère', titleAliases: ['Bar at the Folies-Bergere', 'Un bar aux Folies Bergere'], artist: 'Édouard Manet', year: '1882', movement: 'Realism', alsoMovements: ['Impressionism'], museum: 'Courtauld Gallery, London', fame: 137, wikipedia: 'A_Bar_at_the_Folies-Bergère' },
  { key: 'gross-clinic', title: 'The Gross Clinic', titleAliases: ['Portrait of Dr. Samuel D. Gross', 'Gross Clinic'], artist: 'Thomas Eakins', year: '1875', movement: 'Realism', museum: 'Philadelphia Museum of Art', fame: 143, wikipedia: 'The_Gross_Clinic' },
  { key: 'madame-x', title: 'Madame X', titleAliases: ['Portrait of Madame X', 'Madame Gautreau'], artist: 'John Singer Sargent', year: '1884', movement: 'Realism', alsoMovements: ['Impressionism'], museum: 'Metropolitan Museum of Art, New York', fame: 146, wikipedia: 'Madame_X' },
  { key: 'painters-studio', title: "The Painter's Studio", titleAliases: ["The Artist's Studio", "L'Atelier du peintre"], artist: 'Gustave Courbet', year: '1855', movement: 'Realism', museum: "Musée d'Orsay, Paris", fame: 162, wikipedia: "The_Painter's_Studio" },
  { key: 'third-class-carriage', title: 'The Third-Class Carriage', artist: 'Honoré Daumier', year: 'c. 1862–1864', movement: 'Realism', museum: 'Metropolitan Museum of Art, New York', fame: 185, wikipedia: 'The_Third-Class_Carriage' },
  { key: 'barge-haulers-on-the-volga', title: 'Barge Haulers on the Volga', titleAliases: ['Barge Haulers', 'The Volga Boatmen'], artist: 'Ilya Repin', year: '1870–1873', movement: 'Realism', museum: 'Russian Museum, St Petersburg', fame: 206, wikipedia: 'Barge_Haulers_on_the_Volga' },
  { key: 'horse-fair', title: 'The Horse Fair', titleAliases: ['Horse Fair'], artist: 'Rosa Bonheur', year: '1852–1855', movement: 'Realism', museum: 'Metropolitan Museum of Art, New York', fame: 221, wikipedia: 'The_Horse_Fair' },
  { key: 'gulf-stream', title: 'The Gulf Stream', titleAliases: ['Gulf Stream'], artist: 'Winslow Homer', year: '1899', movement: 'Realism', museum: 'Metropolitan Museum of Art, New York', fame: 234, wikipedia: 'The_Gulf_Stream' },
  // Pre-Raphaelite
  { key: 'ophelia', title: 'Ophelia', artist: 'John Everett Millais', year: '1851–1852', movement: 'Pre-Raphaelite', museum: 'Tate Britain, London', fame: 27, wikipedia: 'Ophelia' },
  { key: 'lady-of-shalott', title: 'The Lady of Shalott', titleAliases: ['Lady of Shalott'], artist: 'John William Waterhouse', year: '1888', movement: 'Pre-Raphaelite', museum: 'Tate Britain, London', fame: 67, wikipedia: 'The_Lady_of_Shalott' },
  { key: 'light-of-the-world', title: 'The Light of the World', titleAliases: ['Light of the World'], artist: 'William Holman Hunt', year: '1851–1853', movement: 'Pre-Raphaelite', museum: 'Keble College, Oxford', fame: 89, wikipedia: 'The_Light_of_the_World' },
  { key: 'proserpine', title: 'Proserpine', artist: 'Dante Gabriel Rossetti', year: '1874', movement: 'Pre-Raphaelite', alsoMovements: ['Symbolism & Art Nouveau'], museum: 'Tate Britain, London', fame: 163, wikipedia: 'Proserpine' },
  { key: 'beata-beatrix', title: 'Beata Beatrix', artist: 'Dante Gabriel Rossetti', year: 'c. 1864–1870', movement: 'Pre-Raphaelite', alsoMovements: ['Symbolism & Art Nouveau'], museum: 'Tate Britain, London', fame: 186, wikipedia: 'Beata_Beatrix' },
  { key: 'last-of-england', title: 'The Last of England', titleAliases: ['Last of England'], artist: 'Ford Madox Brown', year: '1852–1855', movement: 'Pre-Raphaelite', museum: 'Birmingham Museum and Art Gallery', fame: 207, wikipedia: 'The_Last_of_England' },
  { key: 'golden-stairs', title: 'The Golden Stairs', artist: 'Edward Burne-Jones', year: '1880', movement: 'Pre-Raphaelite', alsoMovements: ['Symbolism & Art Nouveau'], museum: 'Tate Britain, London', fame: 222, wikipedia: 'The_Golden_Stairs' },
  // Impressionism
  { key: 'water-lilies', title: 'Water Lilies (Orangerie)', titleAliases: ['Water Lilies', 'Nympheas', 'Les Nympheas'], artist: 'Claude Monet', year: '1914–1926', movement: 'Impressionism', museum: "Musée de l'Orangerie, Paris", fame: 12, wikipedia: 'Water_Lilies_(Monet_series)', crop: { left: 0, top: 0, width: 1, height: 1 } },
  { key: 'impression-sunrise', title: 'Impression, Sunrise', titleAliases: ['Impression Sunrise', 'Impression soleil levant'], artist: 'Claude Monet', year: '1872', movement: 'Impressionism', museum: 'Musée Marmottan Monet, Paris', fame: 19, wikipedia: 'Impression,_Sunrise' },
  { key: 'bal-du-moulin', title: 'Bal du moulin de la Galette', titleAliases: ['Dance at Le Moulin de la Galette', 'Moulin de la Galette'], artist: 'Pierre-Auguste Renoir', year: '1876', movement: 'Impressionism', museum: "Musée d'Orsay, Paris", fame: 33, wikipedia: 'Bal_du_moulin_de_la_Galette' },
  { key: 'luncheon-of-the-boating-party', title: 'Luncheon of the Boating Party', titleAliases: ['Le Dejeuner des canotiers'], artist: 'Pierre-Auguste Renoir', year: '1880–1881', movement: 'Impressionism', museum: 'Phillips Collection, Washington', fame: 34, wikipedia: 'Luncheon_of_the_Boating_Party' },
  { key: 'woman-with-a-parasol', title: 'Woman with a Parasol', titleAliases: ['Woman with a Parasol – Madame Monet and Her Son', 'The Stroll', 'The Promenade'], artist: 'Claude Monet', year: '1875', movement: 'Impressionism', museum: 'National Gallery of Art, Washington', fame: 68, wikipedia: 'Woman_with_a_Parasol' },
  { key: 'water-lily-pond', title: 'The Water-Lily Pond', titleAliases: ['Water-Lily Pond', 'The Japanese Footbridge', 'Bridge over a Pond of Water Lilies'], artist: 'Claude Monet', year: '1899', movement: 'Impressionism', museum: 'National Gallery, London', fame: 90, wikipedia: 'The_Water-Lily_Pond' },
  { key: 'ballet-class', title: 'The Ballet Class', titleAliases: ['Ballet Class', 'The Dance Class'], artist: 'Edgar Degas', year: 'c. 1871–1874', movement: 'Impressionism', museum: "Musée d'Orsay, Paris", fame: 111, wikipedia: 'The_Ballet_Class' },
  { key: 'absinthe', title: "L'Absinthe", titleAliases: ['In a Cafe', 'The Absinthe Drinker', 'Absinthe'], artist: 'Edgar Degas', year: '1875–1876', movement: 'Impressionism', alsoMovements: ['Realism'], museum: "Musée d'Orsay, Paris", fame: 127, wikipedia: "L'Absinthe" },
  { key: 'paris-street-rainy-day', title: 'Paris Street; Rainy Day', titleAliases: ['Paris Street Rainy Day', 'Paris Street in Rainy Weather'], artist: 'Gustave Caillebotte', year: '1877', movement: 'Impressionism', alsoMovements: ['Realism'], museum: 'Art Institute of Chicago', fame: 138, wikipedia: 'Paris_Street;_Rainy_Day' },
  { key: 'boulevard-montmartre', title: 'Boulevard Montmartre at Night', artist: 'Camille Pissarro', year: '1897', movement: 'Impressionism', museum: 'National Gallery, London', fame: 164, wikipedia: 'Boulevard_Montmartre_at_Night' },
  { key: 'flood-at-port-marly', title: 'Flood at Port-Marly', artist: 'Alfred Sisley', year: '1876', movement: 'Impressionism', museum: "Musée d'Orsay, Paris", fame: 187, wikipedia: 'Flood_at_Port-Marly' },
  { key: 'cradle', title: 'The Cradle', titleAliases: ['Le Berceau'], artist: 'Berthe Morisot', year: '1872', movement: 'Impressionism', museum: "Musée d'Orsay, Paris", fame: 208, wikipedia: 'The_Cradle' },
  { key: 'childs-bath', title: "The Child's Bath", titleAliases: ['The Bath'], artist: 'Mary Cassatt', year: '1893', movement: 'Impressionism', museum: 'Art Institute of Chicago', fame: 223, wikipedia: "The_Child's_Bath" },
  { key: 'floor-scrapers', title: 'The Floor Scrapers', artist: 'Gustave Caillebotte', year: '1875', movement: 'Impressionism', alsoMovements: ['Realism'], museum: "Musée d'Orsay, Paris", fame: 235, wikipedia: 'The_Floor_Scrapers' },
  // Post-Impressionism
  { key: 'starry-night', title: 'The Starry Night', titleAliases: ['Starry Night'], artist: 'Vincent van Gogh', year: '1889', movement: 'Post-Impressionism', museum: 'Museum of Modern Art, New York', fame: 2, wikipedia: 'The_Starry_Night' },
  { key: 'sunflowers', title: 'Sunflowers', titleAliases: ['Vase with Fifteen Sunflowers', 'The Sunflowers'], artist: 'Vincent van Gogh', year: '1888', movement: 'Post-Impressionism', museum: 'National Gallery, London', fame: 13, wikipedia: 'Sunflowers_(Van_Gogh_series)' },
  { key: 'grande-jatte', title: 'A Sunday Afternoon on the Island of La Grande Jatte', titleAliases: ['A Sunday on La Grande Jatte', 'La Grande Jatte', 'Sunday Afternoon on the Island of La Grande Jatte'], artist: 'Georges Seurat', year: '1884–1886', movement: 'Post-Impressionism', museum: 'Art Institute of Chicago', fame: 20, wikipedia: 'A_Sunday_Afternoon_on_the_Island_of_La_Grande_Jatte' },
  { key: 'cafe-terrace-at-night', title: 'Café Terrace at Night', titleAliases: ['Cafe Terrace', 'Terrace of a Cafe at Night'], artist: 'Vincent van Gogh', year: '1888', movement: 'Post-Impressionism', museum: 'Kröller-Müller Museum, Otterlo', fame: 30, wikipedia: 'Café_Terrace_at_Night' },
  { key: 'where-do-we-come-from', title: 'Where Do We Come From? What Are We? Where Are We Going?', titleAliases: ['Where Do We Come From'], artist: 'Paul Gauguin', year: '1897–1898', movement: 'Post-Impressionism', alsoMovements: ['Symbolism & Art Nouveau'], museum: 'Museum of Fine Arts, Boston', fame: 43, wikipedia: 'Where_Do_We_Come_From?_What_Are_We?_Where_Are_We_Going?' },
  { key: 'card-players', title: 'The Card Players', titleAliases: ['Card Players'], artist: 'Paul Cézanne', year: '1894–1895', movement: 'Post-Impressionism', museum: "Musée d'Orsay, Paris", fame: 44, wikipedia: 'The_Card_Players' },
  { key: 'self-portrait-bandaged-ear', title: 'Self-Portrait with Bandaged Ear', titleAliases: ['Self-Portrait with Bandaged Ear and Pipe'], artist: 'Vincent van Gogh', year: '1889', movement: 'Post-Impressionism', museum: 'Courtauld Gallery, London', fame: 46, wikipedia: 'Self-Portrait_with_Bandaged_Ear' },
  { key: 'mont-sainte-victoire', title: 'Mont Sainte-Victoire', titleAliases: ['Mont Sainte Victoire', 'Montagne Sainte-Victoire'], artist: 'Paul Cézanne', year: '1902–1904', movement: 'Post-Impressionism', museum: 'Philadelphia Museum of Art', fame: 69, wikipedia: 'Mont_Sainte-Victoire' },
  { key: 'large-bathers', title: 'The Large Bathers', titleAliases: ['Les Grandes Baigneuses', 'Large Bathers'], artist: 'Paul Cézanne', year: '1898–1905', movement: 'Post-Impressionism', museum: 'Philadelphia Museum of Art', fame: 91, wikipedia: 'The_Large_Bathers' },
  { key: 'vision-after-the-sermon', title: 'Vision after the Sermon', titleAliases: ['Jacob Wrestling with the Angel', 'The Vision after the Sermon'], artist: 'Paul Gauguin', year: '1888', movement: 'Post-Impressionism', alsoMovements: ['Symbolism & Art Nouveau'], museum: 'Scottish National Gallery, Edinburgh', fame: 112, wikipedia: 'Vision_after_the_Sermon' },
  { key: 'at-the-moulin-rouge', title: 'At the Moulin Rouge', artist: 'Henri de Toulouse-Lautrec', year: '1892–1895', movement: 'Post-Impressionism', museum: 'Art Institute of Chicago', fame: 128, wikipedia: 'At_the_Moulin_Rouge' },
  { key: 'sleeping-gypsy', title: 'The Sleeping Gypsy', titleAliases: ['Sleeping Gypsy', 'La Bohemienne endormie'], artist: 'Henri Rousseau', year: '1897', movement: 'Post-Impressionism', museum: 'Museum of Modern Art, New York', fame: 139, wikipedia: 'The_Sleeping_Gypsy' },
  { key: 'bathers-at-asnieres', title: 'Bathers at Asnières', titleAliases: ['Bathers at Asnieres', 'Une Baignade, Asnieres'], artist: 'Georges Seurat', year: '1884', movement: 'Post-Impressionism', museum: 'National Gallery, London', fame: 165, wikipedia: 'Bathers_at_Asnières' },
  { key: 'tiger-in-a-tropical-storm', title: 'Tiger in a Tropical Storm (Surprised!)', titleAliases: ['Surprised!', 'Tiger in a Tropical Storm'], artist: 'Henri Rousseau', year: '1891', movement: 'Post-Impressionism', museum: 'National Gallery, London', fame: 188, wikipedia: 'Tiger_in_a_Tropical_Storm_(Surprised!)' },
  // Symbolism & Art Nouveau
  { key: 'scream', title: 'The Scream', titleAliases: ['Skrik', 'The Cry'], artist: 'Edvard Munch', year: '1893', movement: 'Symbolism & Art Nouveau', alsoMovements: ['Expressionism'], museum: 'National Museum, Oslo', fame: 5, wikipedia: 'The_Scream' },
  { key: 'kiss', title: 'The Kiss', titleAliases: ['Der Kuss'], artist: 'Gustav Klimt', year: '1907–1908', movement: 'Symbolism & Art Nouveau', museum: 'Belvedere, Vienna', fame: 10, wikipedia: 'The_Kiss_(Klimt)' },
  { key: 'portrait-of-adele-bloch-bauer', title: 'Portrait of Adele Bloch-Bauer I', titleAliases: ['Adele Bloch-Bauer I', 'The Woman in Gold', 'Woman in Gold', 'The Lady in Gold'], artist: 'Gustav Klimt', year: '1907', movement: 'Symbolism & Art Nouveau', museum: 'Neue Galerie, New York', fame: 70, wikipedia: 'Portrait_of_Adele_Bloch-Bauer_I' },
  { key: 'isle-of-the-dead', title: 'Isle of the Dead', titleAliases: ['Die Toteninsel', 'The Isle of the Dead'], artist: 'Arnold Böcklin', year: '1880', movement: 'Symbolism & Art Nouveau', museum: 'Kunstmuseum Basel', fame: 92, wikipedia: 'Isle_of_the_Dead' },
  { key: 'madonna-munch', title: 'Madonna', artist: 'Edvard Munch', year: '1894', movement: 'Symbolism & Art Nouveau', alsoMovements: ['Expressionism'], museum: 'Munch Museum, Oslo', fame: 166, wikipedia: 'Madonna_(Munch)' },
  { key: 'judith-i', title: 'Judith I', titleAliases: ['Judith and the Head of Holofernes'], artist: 'Gustav Klimt', year: '1901', movement: 'Symbolism & Art Nouveau', museum: 'Belvedere, Vienna', fame: 189, wikipedia: 'Judith_I' },
  { key: 'apparition', title: 'The Apparition', artist: 'Gustave Moreau', year: '1876', movement: 'Symbolism & Art Nouveau', museum: "Musée d'Orsay, Paris", fame: 209, wikipedia: 'The_Apparition' },
  { key: 'cyclops', title: 'The Cyclops', artist: 'Odilon Redon', year: 'c. 1914', movement: 'Symbolism & Art Nouveau', museum: 'Kröller-Müller Museum, Otterlo', fame: 224, wikipedia: 'The_Cyclops' },
  { key: 'demon-seated', title: 'The Demon Seated', titleAliases: ['Demon Seated', 'Seated Demon'], artist: 'Mikhail Vrubel', year: '1890', movement: 'Symbolism & Art Nouveau', museum: 'Tretyakov Gallery, Moscow', fame: 236, wikipedia: 'The_Demon_Seated' },
  // Fauvism
  { key: 'dance-matisse', title: 'The Dance', titleAliases: ['Dance', 'La Danse', 'Dance (II)'], artist: 'Henri Matisse', year: '1910', movement: 'Fauvism', museum: 'Hermitage, St Petersburg', fame: 48, wikipedia: 'Dance_(Matisse)' },
  { key: 'woman-with-a-hat', title: 'Woman with a Hat', artist: 'Henri Matisse', year: '1905', movement: 'Fauvism', museum: 'San Francisco Museum of Modern Art', fame: 71, wikipedia: 'Woman_with_a_Hat' },
  { key: 'joy-of-life', title: 'The Joy of Life', titleAliases: ['Le Bonheur de vivre', 'Joy of Life'], artist: 'Henri Matisse', year: '1905–1906', movement: 'Fauvism', museum: 'Barnes Foundation, Philadelphia', fame: 93, wikipedia: 'The_Joy_of_Life' },
  { key: 'harmony-in-red', title: 'Harmony in Red', titleAliases: ['The Red Room', 'La Desserte'], artist: 'Henri Matisse', year: '1908', movement: 'Fauvism', museum: 'Hermitage, St Petersburg', fame: 167, wikipedia: 'Harmony_in_Red' },
  { key: 'charing-cross-bridge', title: 'Charing Cross Bridge', artist: 'André Derain', year: '1906', movement: 'Fauvism', museum: 'National Gallery of Art, Washington', fame: 190, wikipedia: 'Charing_Cross_Bridge' },
  { key: 'posters-trouville', title: 'The Posters at Trouville', artist: 'Raoul Dufy', year: '1906', movement: 'Fauvism', museum: 'Centre Pompidou, Paris', fame: 210, wikipedia: 'The_Posters_at_Trouville' },
  // Expressionism
  { key: 'street-dresden', title: 'Street, Dresden', titleAliases: ['Street Dresden'], artist: 'Ernst Ludwig Kirchner', year: '1908', movement: 'Expressionism', museum: 'Museum of Modern Art, New York', fame: 72, wikipedia: 'Street,_Dresden' },
  { key: 'large-blue-horses', title: 'The Large Blue Horses', titleAliases: ['Large Blue Horses', 'Die grossen blauen Pferde'], artist: 'Franz Marc', year: '1911', movement: 'Expressionism', museum: 'Walker Art Center, Minneapolis', fame: 94, wikipedia: 'The_Large_Blue_Horses' },
  { key: 'death-and-the-maiden', title: 'Death and the Maiden', artist: 'Egon Schiele', year: '1915', movement: 'Expressionism', museum: 'Belvedere, Vienna', fame: 113, wikipedia: 'Death_and_the_Maiden' },
  { key: 'berlin-street-scene', title: 'Berlin Street Scene', artist: 'Ernst Ludwig Kirchner', year: '1913', movement: 'Expressionism', museum: 'Neue Galerie, New York', fame: 168, wikipedia: 'Berlin_Street_Scene' },
  { key: 'fate-of-the-animals', title: 'Fate of the Animals', titleAliases: ['The Fate of the Animals', 'Tierschicksale'], artist: 'Franz Marc', year: '1913', movement: 'Expressionism', alsoMovements: ['Cubism & Futurism'], museum: 'Kunstmuseum Basel', fame: 191, wikipedia: 'Fate_of_the_Animals' },
  { key: 'self-portrait-physalis', title: 'Self-Portrait with Physalis', titleAliases: ['Self-Portrait with Chinese Lantern Plant'], artist: 'Egon Schiele', year: '1912', movement: 'Expressionism', museum: 'Leopold Museum, Vienna', fame: 211, wikipedia: 'Self-Portrait_with_Physalis' },
  { key: 'self-portrait-modersohn-becker', title: 'Self-Portrait on Her Sixth Wedding Anniversary', artist: 'Paula Modersohn-Becker', year: '1906', movement: 'Expressionism', museum: 'Paula Modersohn-Becker Museum, Bremen', fame: 225, wikipedia: 'Self-Portrait_on_Her_Sixth_Wedding_Anniversary' },
  { key: 'night', title: 'The Night', titleAliases: ['Die Nacht', 'Night'], artist: 'Max Beckmann', year: '1918–1919', movement: 'Expressionism', museum: 'Kunstsammlung Nordrhein-Westfalen, Düsseldorf', fame: 237, wikipedia: 'The_Night' },
  { key: 'carcass-of-beef', title: 'Carcass of Beef', titleAliases: ['Le Boeuf', 'Side of Beef'], artist: 'Chaïm Soutine', year: 'c. 1925', movement: 'Expressionism', museum: 'Buffalo AKG Art Museum', fame: 242, wikipedia: 'Carcass_of_Beef' },
  { key: 'jeanne-hebuterne', title: 'Jeanne Hébuterne', artist: 'Amedeo Modigliani', year: '1919', movement: 'Expressionism', museum: 'Metropolitan Museum of Art, New York', fame: 245, wikipedia: 'Jeanne_Hébuterne' },
  // Cubism & Futurism
  { key: 'portrait-of-picasso', title: 'Portrait of Pablo Picasso', artist: 'Juan Gris', year: '1912', movement: 'Cubism & Futurism', museum: 'Art Institute of Chicago', fame: 73, wikipedia: 'Portrait_of_Pablo_Picasso' },
  { key: 'city-rises', title: 'The City Rises', titleAliases: ['City Rises', 'La citta che sale'], artist: 'Umberto Boccioni', year: '1910', movement: 'Cubism & Futurism', museum: 'Museum of Modern Art, New York', fame: 95, wikipedia: 'The_City_Rises' },
  { key: 'still-life-with-checked-tablecloth', title: 'Still Life with Checked Tablecloth', artist: 'Juan Gris', year: '1915', movement: 'Cubism & Futurism', museum: 'Metropolitan Museum of Art, New York', fame: 169, wikipedia: 'Still_Life_with_Checked_Tablecloth' },
  { key: 'the-city-leger', title: 'The City', artist: 'Fernand Léger', year: '1919', movement: 'Cubism & Futurism', museum: 'Philadelphia Museum of Art', fame: 192, wikipedia: 'The_City_(Léger)' },
  { key: 'champ-de-mars-the-red', title: 'Champ de Mars: The Red Tower', titleAliases: ['The Red Tower', 'Red Eiffel Tower', 'Champ de Mars'], artist: 'Robert Delaunay', year: '1911', movement: 'Cubism & Futurism', museum: 'Art Institute of Chicago', fame: 212, wikipedia: 'Champ_de_Mars:_The_Red_Tower' },
  { key: 'homage-to-bleriot', title: 'Homage to Blériot', titleAliases: ['Homage to Bleriot', 'Hommage a Bleriot'], artist: 'Robert Delaunay', year: '1914', movement: 'Cubism & Futurism', alsoMovements: ['Abstraction'], museum: 'Kunstmuseum Basel', fame: 226, wikipedia: 'Homage_to_Blériot' },
  { key: 'man-on-a-balcony', title: 'Man on a Balcony', artist: 'Albert Gleizes', year: '1912', movement: 'Cubism & Futurism', museum: 'Philadelphia Museum of Art', fame: 238, wikipedia: 'Man_on_a_Balcony' },
  // Abstraction
  { key: 'black-square', title: 'Black Square', titleAliases: ['Black Suprematic Square'], artist: 'Kazimir Malevich', year: '1915', movement: 'Abstraction', museum: 'Tretyakov Gallery, Moscow', fame: 31, wikipedia: 'Black_Square' },
  { key: 'mondrian-composition', title: 'Composition with Red, Blue and Yellow', titleAliases: ['Composition II in Red, Blue, and Yellow', 'Composition with Red Blue and Yellow'], artist: 'Piet Mondrian', year: '1930', movement: 'Abstraction', museum: 'Kunsthaus Zürich', fame: 32, wikipedia: 'Composition_with_Red,_Blue_and_Yellow' },
  { key: 'composition-vii', title: 'Composition VII', artist: 'Wassily Kandinsky', year: '1913', movement: 'Abstraction', alsoMovements: ['Expressionism'], museum: 'Tretyakov Gallery, Moscow', fame: 49, wikipedia: 'Composition_VII' },
  { key: 'several-circles', title: 'Several Circles', titleAliases: ['Einige Kreise'], artist: 'Wassily Kandinsky', year: '1926', movement: 'Abstraction', museum: 'Guggenheim Museum, New York', fame: 74, wikipedia: 'Several_Circles' },
  { key: 'white-on-white', title: 'White on White', titleAliases: ['Suprematist Composition: White on White', 'White on White (Malevich)'], artist: 'Kazimir Malevich', year: '1918', movement: 'Abstraction', museum: 'Museum of Modern Art, New York', fame: 96, wikipedia: 'White_on_White' },
  { key: 'ten-largest-adulthood', title: 'The Ten Largest, No. 7, Adulthood', titleAliases: ['The Ten Largest', 'Adulthood', 'The Ten Largest No. 7'], artist: 'Hilma af Klint', year: '1907', movement: 'Abstraction', museum: 'Hilma af Klint Foundation, Stockholm', fame: 114, wikipedia: 'The_Ten_Largest,_No._7,_Adulthood' },
  { key: 'composition-viii', title: 'Composition VIII', artist: 'Wassily Kandinsky', year: '1923', movement: 'Abstraction', museum: 'Guggenheim Museum, New York', fame: 170, wikipedia: 'Composition_VIII' },
  { key: 'senecio', title: 'Senecio', artist: 'Paul Klee', year: '1922', movement: 'Abstraction', alsoMovements: ['Expressionism'], museum: 'Kunstmuseum Basel', fame: 193, wikipedia: 'Senecio' },
];

/** Cross-artist look-alikes (same-artist works are added automatically). */
export const SUBJECT_PAIRS: [string, string][] = [
  ['judith-caravaggio', 'judith-gentileschi'], ['judith-caravaggio', 'judith-i'], ['judith-gentileschi', 'judith-i'],
  ['last-supper', 'last-supper-tintoretto'], ['venus-of-urbino', 'sleeping-venus'], ['venus-of-urbino', 'rokeby-venus'],
  ['venus-of-urbino', 'olympia'], ['grande-odalisque', 'olympia'], ['nude-maja', 'olympia'], ['annunciation-martini', 'annunciation-angelico'],
  ['lamentation-giotto', 'lamentation-mantegna'], ['maesta', 'ognissanti-madonna'], ['holy-trinity', 'rublev-trinity'],
  ['raft-of-the-medusa', 'liberty-leading-the-people'], ['third-of-may', 'liberty-leading-the-people'], ['ninth-wave', 'raft-of-the-medusa'],
  ['self-portrait-durer', 'self-portrait-two-circles'], ['self-portrait-two-circles', 'self-portrait-bandaged-ear'], ['self-portrait-leyster', 'laughing-cavalier'],
  ['self-portrait-physalis', 'self-portrait-modersohn-becker'], ['self-portrait-straw-hat', 'self-portrait-allegory-painting'],
  ['sudden-shower', 'great-wave'], ['plum-park', 'irises-korin'], ['travelers-mountains', 'early-spring'], ['fuchun-mountains', 'early-spring'],
  ['qingming', 'inwang-clearing'], ['gleaners', 'burial-at-ornans'], ['absinthe', 'bar-folies-bergere'], ['paris-street-rainy-day', 'boulevard-montmartre'],
  ['grande-jatte', 'bal-du-moulin'], ['mondrian-composition', 'black-square'], ['city-rises', 'the-city-leger'], ['portrait-of-picasso', 'man-on-a-balcony'],
  ['woman-with-a-hat', 'posters-trouville'], ['ophelia', 'lady-of-shalott'], ['wanderer', 'oxbow'], ['milkmaid', 'courtyard-delft'],
  ['view-of-delft', 'windmill-wijk'], ['ambassadors', 'arnolfini'], ['tower-of-babel', 'garden-of-earthly-delights'], ['swing', 'pilgrimage-to-cythera'],
  ['blue-boy', 'charles-i-hunt'], ['death-of-general-wolfe', 'watson-and-the-shark'], ['whistlers-mother', 'madame-x'], ['gross-clinic', 'anatomy-lesson'],
  ['cheat-ace-of-diamonds', 'calling-of-st-matthew'], ['las-meninas', 'art-of-painting'], ['innocent-x', 'castiglione'], ['scream', 'death-and-the-maiden'],
  ['composition-vii', 'senecio'], ['ten-largest-adulthood', 'several-circles'], ['large-blue-horses', 'dance-matisse'],
];
